title: The Penguin Coders
author: Mohit Singh
email: mohit@penguincoders.net
description: > # this means to ignore newlines until "twitter_username:"
  Exploring web development, AWS technologies, or taking a deep dive into any tech that captivates my interest.

# social links
twitter_username: msindev
github_username:  msindev
#rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: msindev
# pinterest_username: jekyll
#youtube_username: PenguinCodersNetOfficial
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
