#docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:stable jekyll serve

services:
  jekyll:
    image: jekyll/jekyll:stable
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve
